### ISSUE TITLE
Pop-up window grabs focus, disregarding setting. 

### ISSUE THREAD

**Issue by yourmom2002** [rampaa/JL#16] opened 2022-03-24 12:19 UTC
steps to replicate: 
-just use JL normally 
-after some amount of time pop-up window grabs attention even with "focus on lookup" set to "off" 
-bug disappears whenever i switch to another window / open settings, just like in video 
Bug also occured even before 1.5 update.

https://user-images.githubusercontent.com/99648105/159914353-f849d01b-390d-4900-8e60-89109b19499b.mp4

**Comment by rampaa** [comment] 2022-03-25 15:57
Tried reading the same game with JL for 5 minutes but can't reproduce the problem. How long did you use JL before encountering this behavior? Can you reliably reproduce this behavior within a specific period of time?

**Comment by yourmom2002** [comment] 2022-03-25 16:16
> How long did you use JL before encountering this behavior?

Depends, sometimes it's 30 minutes and sometimes few hours. 

> Can you reliably reproduce this behavior within a specific period of time?

Not really, it's random so far. I'll try to do more experiments later. 

> Tried reading the same game with JL for 5 minutes but can't reproduce the problem

Actually not realated to this specific vn, sorry for confusion. I was reading nukitashi, noticed this behaviour and run asairo just to record video, to make bug demonstration more obvious.

**Comment by yourmom2002** [comment] 2022-04-02 14:30
Accidentally found one way to trigger this bug so far. Not sure if this is what caused bug on video in the first place, but: 
1) Click on JL main window to focus
2) Hover mouse over any word, enter maining mode
3) Exit maining mode by pressing ESC
4) VN window regains focus right away by itself, but each lookup grabs focus with pop-up window.
 
Bug won't get triggered if i exit mining mode by clicking on JL main window again, instead of pressing esc.

**Comment by rampaa** [comment] 2022-04-02 23:15
Thanks, I can reproduce the problem with the steps you've provided. Should be fixed in version 1.9.

**Closed** 2022-04-12 20:24 UTC
Labels: bug
